apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: main
    chart: loki-stack
    helm:
      valueFiles:
        - ../arg-demo/loki/values.yaml  # Relative path to your custom values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring  # Deploying to monitoring namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
